# Generated by Django 3.2 on 2021-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('avatarUrl', models.CharField(max_length=255, verbose_name='用户头像地址')),
            ],
        ),
    ]
